### ISSUE TITLE
Part Time jobs

### ISSUE THREAD

**Issue by kevindavee** [remoteintech/remote-jobs#1141]
Hi,

I found that this is a helpful Github repo. Thanks! 
Wondering if you can add some remote part-time roles as well to this repo?

**Comment by dougaitken** [comment]
Hey @kevindavee 

The job of this is that we link to companies, not jobs, so if a company hires for specific roles as Part-Time, this would be handle away from the list. There is no requirement for role time commitment for any company to be included here. 

As for listing "part-time" as a filter, this list is static and job opening as often fluid, so that type of filter isn't currently part of the functionality of this list.
