### ISSUE TITLE
how to filter software developper jobs？

### ISSUE THREAD

**Issue by 9997766** [remoteintech/remote-jobs#1610]
I  am a java engineer, there are too many companies in the list，how to filter？

**Comment by caputchinefrobles** [comment]
At the search bar just go with `org:remoteintech java`, then voilà:
![image](https://user-images.githubusercontent.com/8964036/210462167-248dee39-3301-4a02-9edf-0f685eedc34b.png)

**Comment by KieranRobson** [comment]
Related to #1252

**Comment by dougaitken** [comment]
If you go to the main site - https://remoteintech.company - and use the search box, that will return profiles where a term is used.

This list, on GitHub.com, isn't meant to be how people use the list anymore, ideally in 2023 I can finally point people to the site rather than the main readme on here.
