### ISSUE TITLE
[Bug] Company search is not working properly

### ISSUE THREAD

**Issue by jazzirHussain** [remoteintech/remote-jobs#1689]
The search functionality of the company will only yield the desired results when the complete name is entered. If not, it tends to display unrelated companies instead of the one intended. Please refer to the attached screenshots for further clarification.

**To Reproduce**
- Go to - https://remoteintech.company/
- Search for any company with only half of the name (eg: 10u)
- It does not display the results for the searched company (10up)

**Expected behavior**
The search results should include companies whose names contain the search term as a part of their name.

**Screenshots**
![problem1](https://github.com/remoteintech/remote-jobs/assets/69746137/eec26829-4aa2-427f-b808-07652926176f)
![problem2](https://github.com/remoteintech/remote-jobs/assets/69746137/282f145d-af50-4fe3-ae1e-798b8a1be256)

**Comment by jazzirHussain** [comment]
If the issue is confirmed to be legitimate, please ensure that it is allocated to me.

**Comment by dougaitken** [comment]
Hi @jazzirHussain thanks for reporting, you're correct this is a bug on the front-end.

This is related to #1123 - it's because this doesn't have fuzzy search, i.e. it only searches full strings. 

I'm wanting to move to Jekyll in the next week or so and this will include full search using lunr.js so I'm closing this purely because a solution is coming, not because it's not a proper bug.
