### ISSUE TITLE
Create a GitHub Pages site

### ISSUE THREAD

**Issue by jessicard** [remoteintech/remote-jobs#44]
This may be easier to find/user if it's on a GitHub pages site. I'd pull this out into an org so that it wouldn't be under my username.

**Comment by eddiejaoude** [comment]
Is this still the plan?

To:
- Github pages
- Create an Organisation

**Comment by eddiejaoude** [comment]
I have quickly put together an Angular app and hosted it on GitHub pages, 

- Fork https://github.com/WeRockTech/remote-jobs
- GitHub pages http://werocktech.com/remote-jobs/

It would be good to get the company profile into the main `json` data so that it can be filtered by tech etc

**Comment by dougaitken** [comment]
I like your idea in #88, this would be really useful, and something I think would really help. 

I'd ideally like it to sit on it's own domain, but we can work on that.

**Comment by eddiejaoude** [comment]
Thanks 👍 .

There are only about ~150 company profiles, if we all did a few it would be done in no time. I will start on a few. But rather than putting them in their own `json` files, it would make searching and filtering better if they were part of the main `json` file.

e.g.

```json
[
  {
    "name": "10up",
    "profile": "/company-profiles/10up.md",
    "website": "http://10up.com/",
    "regions": ["Worldwide"],
    "profile": {
       "size": "",
       "remote": "",
       "region": "",
       "bio": "We make websites and content management simple and fun with premiere web design & development consulting services, by contributing to open platforms like WordPress, and by providing tools and products (like PushUp) that make web publishing a cinch. At 10up, we don’t just “make” things – we engineer them. We’re a group of people built to solve problems; made to create; wired to delight. From beautiful pixels to beautiful code, we constantly improve the things around us, applying our passions to our clients’ projects and goals. We’ve had the privilege of working on big web projects for clients as diverse as TechCrunch, ESPN’s FiveThirtyEight and Grantland, SurveyMonkey, Junior Diabetes Research Foundation (JDRF), and Google."
    }
  },
  // ...
]
```

**Comment by dougaitken** [comment]
How would you see contributing continuing? 
People fork the repo, edit the main json file, then open a PR? 

Doing something like this, to add in filtering, would also mean sanitizing a lot of the existing profiles so that things like tech can be filtered well. 

From my own view, as a "non-tech" working in support, I was wanting to add something about a company who were hiring for support roles, even passively.

**Comment by eddiejaoude** [comment]
> How would you see contributing continuing?
> People fork the repo, edit the main json file, then open a PR?

Yep, same as now.

> sanitizing a lot of the existing profiles

Yes, the data would have to be sanitised better, for example timezones etc

> From my own view, as a "non-tech" working in support, I was wanting to add something about a company who were hiring for support roles, even passively.

Additional (optional) fields can be added to the json file and then displayed in the app accordingly

**Comment by dougaitken** [comment]
I'm wondering if I start an organisation purely for this, then it comes away from Jessica's account and can be handled on it's own. I'll give some thought over the week, and let you know @eddiejaoude

**Comment by eddiejaoude** [comment]
ok sounds good 👍 . What are @jessicard thoughts, as its her project?

**Comment by jessicard** [comment]
@dougaitken Please feel free to pull it to an org! You have been doing a great job maintaining this repo and I super appreciate it. Thanks for checking with me @eddiejaoude :) 👍

**Comment by dougaitken** [comment]
I was gonna ping you about this Jessica, we'll need to work to putting this in it's own repo, and the name of that. `remote-jobs` is taken (old and hardly used, but still), but we're more focused on the companies, so `remote-co` & `remote-companies` is available.

**Comment by eddiejaoude** [comment]
I would have the org a bit more general and then have the repo in the org as the same name as not to confuse people, otherwise `remote-jobs/remote-jobs` looks a bit odd and is limiting to what the org can do in the future - just my 2 cents 🤓.

**Comment by mentos** [comment]
@dougaitken sorry for chiming in, but you may be able to [claim ](http://blog.awolski.com/request-your-github-username/) an inactive GH username by contanting their Support department.

**Comment by dougaitken** [comment]
Not at all @mentos, the more help the better! 
🤔 🤔 🤔  Didn't look into that, but worth a thought.

@eddiejaoude I think I/we are doing one thing and doing it well here - finding companies who hire remotely, and sharing those. Totally see what you're saying, but I'm unsure how we can "branch out". 

Open to suggestions!

**Comment by eddiejaoude** [comment]
> @eddiejaoude I think I/we are doing one thing and doing it well here - finding companies who hire remotely, and sharing those. Totally see what you're saying, but I'm unsure how we can "branch out". Open to suggestions!

Not too sure either at the moment 😄.

Possibly list ideas...

- Companies that are **diverse** and **inclusive** (inc. accessibility)
- Companies that **don't use recruiters** (similar to companies that allow people to work remotely, there are some and they should be promoted). As a contractor it is really annoying when a friend recommends you and you go through all the process of getting the role but then forced to go through a recruiter for the paper work and they take their cut but didn't do the introduction
- Companies that allow **flexible time**
- Companies that don't use **windows**
- Companies that hire **contractors**

Just thinking of what I look for in a company.

**Comment by dougaitken** [comment]
@eddiejaoude early thoughts - I had a shower thought that I want to put this in its own org and start a site to tie in with Hacktoberfest 2017 (if that is happening). 

Plan: 

- Think of genius name for new org/website
- Register domain
- Move repo as-is to a new org I create
- Tidy up data as-is (adding company profiles/updating data) and move to new structure in the process
- Plan for new field/additions/etc
- Use Hacktoberfest as an opportunity to get more hands on deck for tidying/moving to new structure

No need to reply right now, I'll loop back around in a few weeks with more fleshed out plans

**Comment by dougaitken** [comment]
Part 1 complete: 

`https://github.com/remoteintech`

Will get a domain soon

**Comment by jonassteinberg1** [comment]
Given that the site is static it is a perfect candidate for hosting via either serverless or S3+CloudFront (easy TLS integration).  I like the domain: remote.work.  If the site becomes more dynamic I'd be happy to help deploy and automate as well.  I'm Jonas btw.  This is by far the best remote list on the entire netz so let me know if there's some grunt work I can help with.

**Comment by dougaitken** [comment]
🤔 💸 ⌨️ 

`remoteintech.company` 

👍

**Comment by nylen** [comment]
This repository is maintained by humans, and things will continue that way [for the foreseeable future](https://en.wikipedia.org/wiki/Technological_singularity).  So we should keep the Markdown files basically intact as the "source of truth" of this collection of data, only normalizing their structure and automating its validation.

Here are the general steps that would be needed to turn the `.md` files that exist today into a searchable, indexed website, while keeping the current process and repository structure more or less intact:

- [ ] Begin creating a script to parse the `.md` files in this repository.  Its first task should be to identify the overall structure of the data, using Markdown headings as keys and their text (single or multi-paragraph) as values.
- [ ] These headings will undoubtedly be inconsistent.  Identify and fix the inconsistencies.  Our script can probably help here.
- [ ] Look for opportunities to create fields that contain structured data like a number.  **Number of employees**, **fields of work** (software, etc).  What do people want to know about each company at a glance?  I think **whether or not the company is fully remote** is also an independent variable.
- [ ] Decide how to store these structured data items.  I think these should be stored within Markdown, because this repository is maintained by humans.  A code block with [`YAML`](http://www.yaml.org/start.html) syntax highlighting could be a good choice here - in its simplest form, YAML has lines like `employees: 550` and `location: worldwide`.
- [ ] Expand the script to parse and validate a full data structure out of every Markdown file, and output HTML for a table of companies and for each company page.
- [ ] Implement continuous integration to ensure that all files remain valid and all necessary data is completed in the expected format by each new pull request.

As I have time outside of my regular work responsibilities, I'd enjoy working on this in October for [Hacktoberfest](https://hacktoberfest.digitalocean.com/).

**Comment by dougaitken** [comment]
@nylen this is beautiful and exactly what I hoped for. 

I was looking around for something as an inspiration to what I have in mind.
I found this previously and like the interaction `http://gifs.joelglovier.com/`

* Single view of company
 * Breakout into linkable own page (like the gifs)
* filterable/searchable as much as possible

**Comment by nylen** [comment]
We're making progress on this!  I've cleaned up the data and built a cool [code](https://github.com/remoteintech/remote-jobs/pull/406) [review](https://github.com/remoteintech/remote-jobs/pull/401) [bot](https://github.com/remoteintech/remote-jobs/pull/397) that helps us keep things organized.

Another thing we should do is make sure that every company has a profile, even if it is minimal.

**Comment by dougaitken** [comment]
> Another thing we should do is make sure that every company has a profile, even if it is minimal.

Yes. 100%
If a company isn't added, the PR should fail the bot check. If someone wants to suggest a company, we should have an Issue opened, which someone else can then reference and create a PR from

**Comment by nylen** [comment]
This repo now has GitHub Pages active, thanks for doing that @dougaitken:  https://remoteintech.github.io/remote-jobs/

I've been playing around with adding basic sorting and filtering that is just based on the content that's already in the main table.  You can see it at https://nylen.github.io/remote-jobs/ and it looks like this:

> <img src="https://user-images.githubusercontent.com/227022/40275979-eea4212e-5bc3-11e8-9e7e-779bdab01def.png" width="500">

The library I'm using is [`list.js`](https://github.com/javve/list.js), it seems pretty nice.  Adding extra filters will be a bit of a challenge though, because we need to get the data for the new filters into the index page somehow.

Ideally these extra filters would not add maintenance burden or too much extra complexity.  Right now we just have to maintain the Markdown files which get pulled straight into GitHub Pages.  Anyone can do it and there is nothing else that needs to be updated afterwards.

I am thinking we can build some kind of thing that runs every time the content in this repo changes and generates a data file from our Markdown profiles (a good bit of the code that would be needed is already in place in [`bin/validate.js`](https://github.com/remoteintech/remote-jobs/blob/e90e0a8/bin/validate.js)).  If anyone has any other ideas let me know.

**Comment by nylen** [comment]
For now, we can push the above basic filtering live on GitHub Pages - @dougaitken what do you think?

For later, I've been researching some options, and I think ultimately we should go with [Netlify](https://www.netlify.com/) for the site.  It works a lot like GitHub Pages in that we push changes to GitHub, and they run a script which automatically updates the website.  Unlike GitHub Pages, though, the site build is fully customizable, which would allow us to achieve what I outlined above without too much trouble.  They'll also provide other nice things like site previews for GitHub PRs, and the free plan will be more than enough to meet our needs.

So I'll work on a static site generator over the next couple months.  A lot of the code we'll need is already in place, but I'd like to make it more easily testable first.

**Comment by dougaitken** [comment]
Sounds good, I "know" someone on the Netlify team and have seen a lot of positive things about them recently on Twitter so let's do it.

Ship the filtering if you feel it's ready. 

Let's use https://github.com/remoteintech/remote-jobs/projects/3 for each section and create a new Issue to base off

**Comment by nylen** [comment]
Now that we have a basic GitHub Pages site (https://remoteintech.github.io/remote-jobs/), this issue is technically done.  So I'll close this out, but for anyone interested in contributing, there is lots more to do in separate issues in the ["front end search" project](https://github.com/remoteintech/remote-jobs/projects/3).  There are also lots of good ideas for other enhancements in the comments above, which we should keep in mind and create separate issues where needed.
