### ISSUE TITLE
Expand the Search scope to all of the profile rather than name and region

### ISSUE THREAD

**Issue by dougaitken** [remoteintech/remote-jobs#584]
Related to #569 

Currently, when someone wants to search the list, they are limited to name and region. Having the ability to search the whole profile would allow for filtering by technology or another keyword.

**Comment by whatacold** [comment]
Just being curious, where can we search these data from? It takes a lot of time for me to see every company's websites :(.

**Comment by noobyogi0010** [comment]
Hey @dougaitken !
I would like to work on this by adding additional filtering in search. Can you please tell me how to get started with contributing?
Thanks.

**Comment by dougaitken** [comment]
Hey @noobyogi0010 - @nylen is best to confirm but I'm unsure how this should be done. Currently it is a search/filter happening here - https://github.com/remoteintech/remote-jobs/blob/master/site/assets/companies-table.js

For context, this list is compiled into a static site that lives on Netlify.

**Comment by nylen** [comment]
Hi @noobyogi0010, you can see the documentation for how the site is currently built here: https://github.com/remoteintech/remote-jobs/tree/master/site

In order to solve this issue, you'll need to make the data (text) from the rest of the company profile available to the search function on the main page. This is the `companies-table.js` code that Doug mentioned.

I'm not sure the best way to make this work. It will require some custom code and perhaps changing the library that is used for the search.
